repos:
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
- repo: https://github.com/ambv/black
  rev: 23.1.0
  hooks:
  - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort (python)
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'bdfdfda2221c4fd123dbc9ac0f2074951bd5af58'
  hooks:
  - id: mypy
- repo: https://github.com/econchick/interrogate
  rev: 1.5.0  # or master if you're bold
  hooks:
    - id: interrogate
      args: [--quiet, --config=pyproject.toml]