repos:
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
- repo: https://github.com/ambv/black
  rev: 22.1.0
  hooks:
  - id: black
    additional_dependencies: ['click==8.0.4']
- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
  - id: isort
    name: isort (python)
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'bdfdfda2221c4fd123dbc9ac0f2074951bd5af58'
  hooks:
  - id: mypy
repos:
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0  # or master if you're bold
    hooks:
      - id: interrogate
        args: [--quiet -c pyproject.toml]