name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      matrix:
        python-version: ['3.9']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - uses: actions/cache@v1
      with:
        path: ~/.cache/torch
        key: ${{ runner.os }}-cache-torch
    - uses: actions/cache@v1
      with:
        path: ~/.torch
        key: ${{ runner.os }}-torch
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install requirements.txt
      run: |
        function retry-with-backoff() {
          for BACKOFF in 0 1 2 4 8 16 32 64; do
            sleep $BACKOFF
            if "$@"; then
              return 0
            fi
          done
          return 1
        }
        python -m pip install --upgrade pip setuptools wheel
        retry-with-backoff pip install -r requirements_dev.txt
    - name: pylint
      run: |
        pylint shifthappens
        pylint tests
    - name: black
      run: |
        black --check --verbose .
    - name: Install package
      run: |
        pip install -e .
    - name: Install tests/requirements.txt
      run: |
        function retry-with-backoff() {
          for BACKOFF in 0 1 2 4 8 16 32 64; do
            sleep $BACKOFF
            if "$@"; then
              return 0
            fi
          done
          return 1
        }
        retry-with-backoff pip install -r tests/requirements.txt
    - name: mypy (package)
      run: |
        mypy --install-types --non-interactive shifthapens/
        mypy -p shifthappens
    - name: mypy (tests)
      run: |
        mypy tests/
    - name: Test with pytest
      run: |
        pytest --durations=0 --verbose